# Generated by Django 5.0 on 2024-08-07 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_subcateogery_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcateogery',
            name='scat',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcateogery',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.cateogery'),
        ),
    ]
