# Generated by Django 5.0 on 2024-08-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_subcateogery_scat_alter_subcateogery_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcateogery',
            old_name='cat',
            new_name='ccat',
        ),
    ]
